//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.SP.IntranetWeb.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntranetAppsDbEntities : DbContext
    {
        public IntranetAppsDbEntities()
            : base("name=IntranetAppsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DocumentAssignment> DocumentAssignment { get; set; }
        public virtual DbSet<IncomingMailbox> IncomingMailbox { get; set; }
        public virtual DbSet<IncomingMailboxDetail> IncomingMailboxDetail { get; set; }
    }
}
