//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.SP.Intranet.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodingHistory
    {
        public int CodingId { get; set; }
        public int CodingHistoryId { get; set; }
        public string DocumentCode { get; set; }
        public Nullable<System.DateTime> AssignmentDate { get; set; }
        public string AssignedToLogin { get; set; }
        public string AssignedToName { get; set; }
        public string AssignmentSubject { get; set; }
    
        public virtual CodingParameters CodingParameters { get; set; }
    }
}
