//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.SP.Intranet.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentAssignment
    {
        public int DocumentAssignmentId { get; set; }
        public string SiteUrl { get; set; }
        public string DocumentLibraryId { get; set; }
        public Nullable<int> ListItemId { get; set; }
        public string DocumentUrl { get; set; }
        public string DocumentTitle { get; set; }
        public string AssignedByLogin { get; set; }
        public string AssignedByName { get; set; }
        public Nullable<System.DateTime> AssignmentDate { get; set; }
        public string AssignmentStatus { get; set; }
        public string AssignedToLogin { get; set; }
        public string AssignedToName { get; set; }
        public string AssignedToControl { get; set; }
        public Nullable<System.DateTime> DueToDate { get; set; }
        public Nullable<int> FirstReminderDays { get; set; }
        public Nullable<int> SecondReminderDays { get; set; }
        public string DocumentSubject { get; set; }
        public string DocumentAnnotations { get; set; }
    }
}
