//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.SP.Intranet.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboxDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InboxDocument()
        {
            this.InboxDocumentDetail = new HashSet<InboxDocumentDetail>();
        }
    
        public int IncomingMailboxId { get; set; }
        public string SiteUrl { get; set; }
        public string DocumentCode { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string DocumentSubject { get; set; }
        public string CompanyName { get; set; }
        public string DepartmentName { get; set; }
        public string AssignedByLogin { get; set; }
        public string AssignedByName { get; set; }
        public Nullable<System.DateTime> AssignmentDate { get; set; }
        public string DocumentStatus { get; set; }
        public string AssignedToLogin { get; set; }
        public string AssignedToName { get; set; }
        public string AssignedToControl { get; set; }
        public string AssignedToCCLogin { get; set; }
        public string AssignedToCCName { get; set; }
        public string AssignedToCCControl { get; set; }
        public string FromCompany { get; set; }
        public string FromContact { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public string Annotations { get; set; }
        public Nullable<System.DateTime> FirstReminderDate { get; set; }
        public Nullable<System.DateTime> SecondReminderDate { get; set; }
        public string AttachmentUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InboxDocumentDetail> InboxDocumentDetail { get; set; }
    }
}
