//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.SP.Intranet.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutcomingMailbox
    {
        public int OutcomingMailboxId { get; set; }
        public string SiteUrl { get; set; }
        public string DocumentCode { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string RequestedByLogin { get; set; }
        public string RequestedByName { get; set; }
        public string DocumentSubject { get; set; }
        public string CompanyName { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public string DocumentStatus { get; set; }
        public string DocumentFolder { get; set; }
        public string DocumentFilename { get; set; }
        public string ReceiptFilename { get; set; }
        public string DestinationCompany { get; set; }
    }
}
